api:
  title: OASys Web API
  description: Simple API to consume the Ontology Alignment System as a Service
  version: 0.0.1
  port: 8081
  debug: True

  logging:
    level: INFO
    output_dir: data/oasys_api/logs

  inference:
    available_models:
      - configurations/models/sbert_baseline_bert.yaml

  io:
    psg_config: configurations/pseudo_sentence_generator/nlfoa/psg_params_default.yaml
    results_base_dir: data/api/results

  model:
    device: cuda:0
    pertrained_name_or_path: data/train_results/nlfoa/train_nlfoa_oaei_ana-tn_sts-all-mpnet-base-v2_2022-07-26_17:51:44.893957/model
    type: nlfoa
  
  similarity: cosine
  threshold: 0.6
