nlfoa_training_config:
  random_seed: 1312
  io:
    train_set: datasets/nlfoa/veealign/combo/twice_negatives/train.parquet.df
    test_set: datasets/nlfoa/veealign/combo/twice_negatives/test.parquet.df
    val_set: datasets/nlfoa/veealign/combo/twice_negatives/validate.parquet.df
    results_dir: data/train_results/nlfoa/dynamic_ps
  model:
    sts_model: all-mpnet-base-v2
    add_special_tokens: False
    pooling_mode: mean
    device: 'cuda:0'
  training:
    train_batch_size: 16
    test_batch_size: 32
    val_batch_size: 32
    shuffle_dataloaders: True
    dynamic_pseudo_sentences:
      ontologies_glob: datasets/veealign/**/**/*.owl
      psg_config: configurations/pseudo_sentence_generator/nlfoa/psg_params_only_name_desc_props_no_closing_english.yaml
      shuffle_ps: True
    epochs: 20
    evaluation_steps: 500
    checkpoint_save_steps: 333
    loss: CosineSimilarityLoss # see sentence_transformers.losses for options
    warmup_scheduler: WarmupLinear
    warmup_steps: .1 # fraction of training samples
    optimizer: AdamW
    lr: 2e-5
    weight_decay: 0.01
    evaluator: EmbeddingSimilarityEvaluator # see sentence_transformers.evaluation for options
    use_amp: True
