nlfoa_training_config:
  random_seed: 1312
  io:
    train_set: datasets/nlfoa/veealign/combo/train.parquet.df
    test_set: datasets/nlfoa/veealign/combo/test.parquet.df
    val_set: datasets/nlfoa/veealign/combo/validate.parquet.df
    results_dir: data/train_results/nlfoa
  model:
    sts_model: all-mpnet-base-v2
    add_special_tokens: True
    pooling_mode: mean
    device: 'cuda:0'
  training:
    train_batch_size: 16
    test_batch_size: 32
    val_batch_size: 32
    shuffle_dataloaders: True
    epochs: 0
    evaluation_steps: 0
    checkpoint_save_steps: 0
    loss: CosineSimilarityLoss # see sentence_transformers.losses for options
    warmup_scheduler: WarmupLinear
    warmup_steps: .1 # fraction of training samples
    optimizer: AdamW
    lr: 2e-5
    weight_decay: 0.01
    evaluator: EmbeddingSimilarityEvaluator # see sentence_transformers.evaluation for options
    use_amp: True
